GD-912: fix(delete_directory): Remove hidden files (#901)
# Why
Hidden files will prevent a directory from being deleted which causes
errors to be thrown in the console.
For example, the following file was causing the following errors:
`/home/<username>/.local/share/godot/app_userdata/<project_name>/tmp/update/addons/gdUnit4/src/reporters/html/template/.gdignore`
```
ERROR: Delete user://tmp/update/addons/gdUnit4/src/reporters/html/template failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp/update/addons/gdUnit4/src/reporters/html failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp/update/addons/gdUnit4/src/reporters failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp/update/addons/gdUnit4/src failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp/update/addons/gdUnit4 failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp/update/addons failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp/update failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
ERROR: Delete user://tmp failed: Failed
   at: push_error (core/variant/variant_utility.cpp:1098)
```
I'm not sure how `.gdignore` was created in the first place.

# What
Set DirAccess include_hidden = true in `delete_directory` functions.

---------

Co-authored-by: Nullpointer <mikeschulze.lpz@gmail.com>