GD-224: Update project to Godot 4.1.1 (#223)
# Why
We want to support the latest Godot version v4.1.1


# What
- update project to v4.1.1
- add Godot 4.1, 4.1.1 to ci-pr and ci-dev workflows
- update README.md
- fix crash by remove the temporary workaround introduced by
https://github.com/MikeSchulze/gdUnit4/pull/137
- fix crash by do not print messages on plugin `_exit_tree`
(https://github.com/godotengine/godot/issues/79379)
```
malloc(): mismatching next->prev_size (unsorted)
Aborted (core dumped)
Error: Process completed with exit code 134.
```